language: node_js
node_js:
    - "10.0"
branches:
  only:
  - master
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
after_success:
  - "npm run predeploy"
